# [Choice] Debian / Ubuntu version: debian-10, debian-9
ARG VARIANT=buster
FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}


# use the tencent cloud mirror
COPY buster.sources.list /etc/apt/sources.list

